name: 🍎 macOS Production Builds
on:
  workflow_call:

# Global Settings
env:
  # Used for the cache key. Add version suffix to force clean build.
  GODOT_BASE_BRANCH: 4.4
  SCONS_FLAGS: module_text_server_fb_enabled=yes strict_checks=yes production=yes

jobs:
  build-macos:
    runs-on: macos-latest
    name: ${{ matrix.name }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor (target=editor, tests=yes)
            cache-name: macos-editor
            target: editor
            scons-flags: debug_symbols=no
            bin: ./bin/godot.macos.editor.universal
            build-mono: false
            artifact-mono: false

          - name: Template, release (target=template_release, tests=yes)
            cache-name: macos-template-release
            target: template_release
            scons-flags: debug_symbols=no
            bin: ./bin/godot.macos.template_release.universal
            build-mono: false
            artifact-mono: false

          # - name: Template, debug (target=template_debug, tests=yes)
          #   cache-name: macos-template-debug
          #   target: template_debug
          #   scons-flags: debug_symbols=no
          #   bin: ./bin/godot.macos.template_debug.universal

          - name: Editor w/ Mono (target=editor, tests=yes)
            cache-name: macos-editor-mono
            target: editor
            scons-flags: debug_symbols=no module_mono_enabled=yes
            bin: ./bin/godot.macos.editor.universal.mono
            build-mono: true
            artifact-mono: true

          - name: Template w/ Mono, release (target=template_release, tests=yes)
            cache-name: macos-template-mono-release
            target: template_release
            scons-flags: debug_symbols=no module_mono_enabled=yes
            bin: ./bin/godot.macos.template_release.universal.mono
            build-mono: false
            artifact-mono: true

          # - name: Template w/ Mono, debug (target=template_debug, tests=yes)
          #   cache-name: macos-template-mono-debug
          #   target: template_debug
          #   scons-flags: debug_symbols=no module_mono_enabled=yes
          #   bin: ./bin/godot.macos.template_debug.universal.mono
          #   build-mono: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Select Xcode 16
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Restore Godot build cache
        uses: ./.github/actions/godot-cache-restore
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Setup Python and SCons
        uses: ./.github/actions/godot-deps

      - name: Download pre-built AccessKit
        uses: dsaltares/fetch-gh-release-asset@1.1.2
        with:
          repo: AccessKit/accesskit-c
          version: tags/0.17.0
          file: accesskit-c-0.17.0.zip
          target: accesskit-c-0.17.0/accesskit_c.zip

      - name: Extract pre-built AccessKit
        run: unzip -o accesskit-c-0.17.0/accesskit_c.zip

      - name: Setup Vulkan SDK
        id: vulkan-sdk
        run: |
          if sh misc/scripts/install_vulkan_sdk_macos.sh; then
            echo "VULKAN_ENABLED=yes" >> "$GITHUB_OUTPUT"
          else
            echo "::warning::macOS: Vulkan SDK installation failed, building without Vulkan support."
            echo "VULKAN_ENABLED=no" >> "$GITHUB_OUTPUT"
          fi
        continue-on-error: true

      - name: Setup older .NET SDK as baseline
        if: matrix.build-mono
        uses: actions/setup-dotnet@v4
        with:
          # Targeting the oldest version we want to support to ensure it still builds.
          dotnet-version: 8.0.100

      - name: Compilation (x86_64)
        uses: ./.github/actions/godot-build
        with:
          scons-flags: ${{ env.SCONS_FLAGS }} ${{ matrix.scons-flags }} arch=x86_64 vulkan=${{ steps.vulkan-sdk.outputs.VULKAN_ENABLED }}
          platform: macos
          target: ${{ matrix.target }}

      - name: Compilation (arm64)
        uses: ./.github/actions/godot-build
        with:
          scons-flags: ${{ env.SCONS_FLAGS }} ${{ matrix.scons-flags }} arch=arm64 vulkan=${{ steps.vulkan-sdk.outputs.VULKAN_ENABLED }}
          platform: macos
          target: ${{ matrix.target }}

      - name: Save Godot build cache
        uses: ./.github/actions/godot-cache-save
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Prepare artifact
        if: "!matrix.artifact-mono"
        run: |
          lipo -create ./bin/godot.macos.${{ matrix.target }}.x86_64 ./bin/godot.macos.${{ matrix.target }}.arm64 -output ./bin/godot.macos.${{ matrix.target }}.universal
          rm ./bin/godot.macos.${{ matrix.target }}.x86_64 ./bin/godot.macos.${{ matrix.target }}.arm64
          strip bin/godot.*
          chmod +x bin/godot.*

      - name: Prepare artifact (Mono)
        if: matrix.artifact-mono
        run: |
          lipo -create ./bin/godot.macos.${{ matrix.target }}.x86_64.mono ./bin/godot.macos.${{ matrix.target }}.arm64.mono -output ./bin/godot.macos.${{ matrix.target }}.universal.mono
          rm ./bin/godot.macos.${{ matrix.target }}.x86_64.mono ./bin/godot.macos.${{ matrix.target }}.arm64.mono
          strip bin/godot.*
          chmod +x bin/godot.*

      - name: Generate C# glue
        if: matrix.build-mono
        run: |
          ${{ matrix.bin }} --headless --generate-mono-glue ./modules/mono/glue

      - name: Build .NET solutions
        if: matrix.build-mono
        run: |
          dotnet --info
          ./modules/mono/build_scripts/build_assemblies.py --godot-output-dir=./bin --godot-platform=macos --werror

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.cache-name }}

      # - name: Unit tests
      #   run: |
      #     ${{ matrix.bin }} --version
      #     ${{ matrix.bin }} --help
      #     ${{ matrix.bin }} --test --force-colors
